function addcolormappopupmenu(figureHandle, PopUpPosition)
%% ADDCOLORMAPOPUPMENU - adds colormap popup menu to current figure 

if nargin < 2
  PopUpPosition = [.01 .01 .15 .08];
end

colormappanel = uipanel('Parent', figureHandle,...
  'Units', 'Normalized', 'Position', PopUpPosition,...
  'FontWeight', 'bold','BackgroundColor', figureHandle.Color,...
  'Title', 'Background color');
h_colormap = uicontrol('Parent', colormappanel,...
 'Style', 'popup','String', {'parula','jet','hsv','hot','cool',...
 'spring','summer','autumn','winter','gray','bone','copper','pink'},...
 'Units', 'Normalized', 'Position', [0 0 1 1], 'Value',1,...
 'BackgroundColor', figureHandle.Color); 

% Note: setmap is callback saved in separate mfile
set(h_colormap,  'Callback', @setmap)
end