BT549_trajectory_analysis.md:BT549_trajectory_analysis.Rmd
	R -e 'rmarkdown::render("BT549_trajectory_analysis.Rmd", output_format = "md_document")'
	sed -i -e 's+!\[\](+![](https://raw.githubusercontent.com/ocbe-uio/CellMAPtracer/wiki/Wiki/g+g' BT549_trajectory_analysis.md